"""sqlalchemy 2.0 typed model: not null, unique username

Revision ID: e9129316ee33
Revises: 21e948ed5363
Create Date: 2026-09-01 21:43:48.963280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9129316ee33'
down_revision: Union[str, Sequence[str], None] = '21e948ed5363'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               type_=sa.String(length=255),
               nullable=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.alter_column('users', 'password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
